### PR TITLE
JIRA projects allow numbers in their key

### PR DESCRIPTION
**Pull request by neilbartley**
Update regex to allow numbers in the key eg: `FOO5-123`

### CODE REVIEW

**Review by izerlotti — COMMENTED** [review]
We use projects with numbers in the keys, therefore this change will be really appreciated

**Review by avilaton — APPROVED** [review]

**Comment by izerlotti** [comment]
Thank you for merging the changes in main branch, Despite this the tool  is still not working because of the tag v0.0.5
The .pre-commit-config.yaml needs a rev tag and the v0.0.05 one is pointing to an old commit
Could you please add a new tag pointing to the commit containing the change?
Thank you

**Comment by izerlotti** [comment]
Just to inform you that I managed to make it working using the SHA of the commit in the rev tag of the yaml file. I still think it should be better to have a new tag for the revision.
Thank you

**Comment by avilaton** [comment]
https://github.com/avilaton/add-msg-issue-prefix-hook/releases/tag/v0.0.6 done!

**Comment by izerlotti** [comment]
> https://github.com/avilaton/add-msg-issue-prefix-hook/releases/tag/v0.0.6 done!

Thank you so much. It's working perfectly!

**Comment by avilaton** [comment]
Thanks to you!

**Pull request merged**
