### PR TITLE
Fix issue #19 missing new line before comment

### LINKED ISSUE #19: Missing new line after issue prefix
I use the following configuration

```yaml
- repo: https://github.com/avilaton/add-msg-issue-prefix-hook
  rev: v0.0.9
  hooks:
  - id: add-msg-issue-prefix
    args:
    - '--template={}:'
```

The commit message misses the new line after the issue prefix, pulling the Git comment to the first line

```
ABC-123: # Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
```

Version 0.0.6 works fine.

### PR DESCRIPTION
**Pull request by artslob**
Fix #19

### CODE REVIEW

**Comment by artslob** [comment]
@avilaton can you please take a look at this PR?

**Comment by artslob** [comment]
@avilaton would appreciate your review on PR, thank you!

**Comment by ogun-** [comment]
@avilaton A merge of this fix would be appreciated!

**Review by avilaton — APPROVED** [review]

**Comment by avilaton** [comment]
> @avilaton A merge of this fix would be appreciated!

sorry it takes so long, you know how it goes! Merged it

**Comment by artslob** [comment]
All it takes is comment from right person :rofl: Thanks, @ogun-

**Comment by avilaton** [comment]
We need a release right?

**Comment by artslob** [comment]
I guess so. It would be easier to use fix in pre-commit with new version

**Pull request merged**
